name: toeicsoeasy
description: "A Flutter project help you study for TOEIC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  responsive_sizer: ^3.3.1
  dio: ^5.7.0
  dartz: ^0.10.1 # xử lý dữ liệu tải xuống với dartz (Left: chưa thành công, Right: thành công)
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3 # Trình tìm dịch vụ (Easy Dependency Injection with get())

  # database
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/icons/app_icon.png
      - assets/images/icons/studying.png
      - .env

      # icon 
      - assets/images/icons/google.png
      - assets/images/icons/facebook.png
      - assets/images/icons/mail.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

